function v_ij = calc_v(h,i,j) 
%     v_ij = [h(i,1)*h(j,1), ... 
%             h(i,1)*h(j,2)+h(i,2)*h(j,1),... 
%             h(i,2)*h(j,2), ... 
%             h(i,3)*h(j,1)+h(i,1)*h(j,3), ... 
%             h(i,3)*h(j,2) + h(i,2)*h(j,3), ...
%             h(i,3)*h(j,3)];
    v_ij = [h(1,i)*h(1,j), ...
            h(1,i)*h(2,j)+h(2,i)*h(1,j),...
            h(2,i)*h(2,j), ... 
            h(3,i)*h(1,j)+h(1,i)*h(3,j), ... 
            h(3,i)*h(2,j) + h(2,i)*h(3,j), ...
            h(3,i)*h(3,j)];
end